// Faculty options - generic for all Egyptian universities
export const facultyOptions = [
    'Computer Science',
    'Engineering',
    'Computer Engineering',
    'Information Technology',
    'Artificial Intelligence',
    'Information Systems',
    'Software Engineering',
    'Data Science',
    'Cybersecurity',
    'Medicine',
    'Pharmacy',
    'Dentistry',
    'Physical Therapy',
    'Business Administration',
    'Commerce',
    'Economics',
    'Law',
    'Arts',
    'Science',
    'Agriculture',
    'Veterinary Medicine',
    'Education',
    'Nursing',
    'Fine Arts',
    'Mass Communication',
    'Tourism & Hotels',
    'Languages (Alsun)',
    'Archaeology',
    'Other'
].map(opt => ({ label: opt, value: opt }));

export const levelOptions = [
    'Level 1',
    'Level 2',
    'Level 3',
    'Level 4',
    'Level 5',
    'Level 6',
    'Graduate',
    'Postgraduate'
].map(opt => ({ label: opt, value: opt }));

// Common Egyptian university email domains
export const knownUniversityDomains: Record<string, string> = {
    'cu.edu.eg': 'Cairo University',
    'aun.edu.eg': 'Assiut University',
    'alexu.edu.eg': 'Alexandria University',
    'asu.edu.eg': 'Ain Shams University',
    'bu.edu.eg': 'Benha University',
    'fayoum.edu.eg': 'Fayoum University',
    'helwan.edu.eg': 'Helwan University',
    'kfs.edu.eg': 'Kafr El-Sheikh University',
    'mans.edu.eg': 'Mansoura University',
    'menofia.edu.eg': 'Menoufia University',
    'minia.edu.eg': 'Minia University',
    'psas.bsu.edu.eg': 'Beni-Suef University',
    'svu.edu.eg': 'South Valley University',
    'suezuniv.edu.eg': 'Suez University',
    'su.edu.eg': 'Suez Canal University',
    'tanta.edu.eg': 'Tanta University',
    'zu.edu.eg': 'Zagazig University',
    'azhar.edu.eg': 'Al-Azhar University',
    // Private Universities
    'aast.edu.eg': 'Arab Academy for Science & Technology',
    'aucegypt.edu.eg': 'American University in Cairo',
    'bue.edu.eg': 'British University in Egypt',
    'guc.edu.eg': 'German University in Cairo',
    'msa.edu.eg': 'MSA University',
    'ngu.edu.eg': 'Nile University',
    'pua.edu.eg': 'Pharos University',
    'zewailcity.edu.eg': 'Zewail City',
    'horus.edu.eg': 'Horus University',
    'ecu.edu.eg': 'Egyptian Chinese University',
    'fue.edu.eg': 'Future University in Egypt',
    'mti.edu.eg': 'MTI University',
    'o6u.edu.eg': 'October 6 University',
    'miuegypt.edu.eg': 'Misr International University',
    'must.edu.eg': 'Misr University for Science & Technology',
    'nu.edu.eg': 'Nahda University',
    'spu.edu.eg': 'Sphinx University',
};
