import { TrainerScript } from '@/types/trainer';

export const theatreSquareScript: TrainerScript = {
    audioUrl: '/audio/theatre-square-ar.wav',
    events: [
        { timestamp: 100, type: 'type', payload: '#' },
        { timestamp: 200, type: 'type', payload: 'i' },
        { timestamp: 300, type: 'type', payload: 'n' },
        { timestamp: 400, type: 'type', payload: 'c' },
        { timestamp: 500, type: 'type', payload: 'l' },
        { timestamp: 600, type: 'type', payload: 'u' },
        { timestamp: 700, type: 'type', payload: 'd' },
        { timestamp: 800, type: 'type', payload: 'e' },
        { timestamp: 900, type: 'type', payload: ' ' },
        { timestamp: 1000, type: 'type', payload: '<' },
        { timestamp: 1100, type: 'type', payload: 'i' },
        { timestamp: 1200, type: 'type', payload: 'o' },
        { timestamp: 1300, type: 'type', payload: 's' },
        { timestamp: 1350, type: 'type', payload: 't' },
        { timestamp: 1400, type: 'type', payload: 'r' },
        { timestamp: 1450, type: 'type', payload: 'e' },
        { timestamp: 1500, type: 'type', payload: 'a' },
        { timestamp: 1550, type: 'type', payload: 'm' },
        { timestamp: 1580, type: 'type', payload: '>' },
        { timestamp: 1600, type: 'type', payload: '\n' },

        { timestamp: 2100, type: 'type', payload: 'u' },
        { timestamp: 2200, type: 'type', payload: 's' },
        { timestamp: 2300, type: 'type', payload: 'i' },
        { timestamp: 2400, type: 'type', payload: 'n' },
        { timestamp: 2500, type: 'type', payload: 'g' },
        { timestamp: 2600, type: 'type', payload: ' ' },
        { timestamp: 2700, type: 'type', payload: 'n' },
        { timestamp: 2800, type: 'type', payload: 'a' },
        { timestamp: 2850, type: 'type', payload: 'm' },
        { timestamp: 2900, type: 'type', payload: 'e' },
        { timestamp: 2950, type: 'type', payload: 's' },
        { timestamp: 3000, type: 'type', payload: 'p' },
        { timestamp: 3050, type: 'type', payload: 'a' },
        { timestamp: 3100, type: 'type', payload: 'c' },
        { timestamp: 3150, type: 'type', payload: 'e' },
        { timestamp: 3200, type: 'type', payload: ' ' },
        { timestamp: 3250, type: 'type', payload: 's' },
        { timestamp: 3300, type: 'type', payload: 't' },
        { timestamp: 3350, type: 'type', payload: 'd' },
        { timestamp: 3400, type: 'type', payload: ';' },
        { timestamp: 3450, type: 'type', payload: '\n' },
        { timestamp: 3500, type: 'type', payload: '\n' },

        { timestamp: 4100, type: 'type', payload: 'i' },
        { timestamp: 4200, type: 'type', payload: 'n' },
        { timestamp: 4300, type: 'type', payload: 't' },
        { timestamp: 4400, type: 'type', payload: ' ' },
        { timestamp: 4500, type: 'type', payload: 'm' },
        { timestamp: 4600, type: 'type', payload: 'a' },
        { timestamp: 4700, type: 'type', payload: 'i' },
        { timestamp: 4800, type: 'type', payload: 'n' },
        { timestamp: 4850, type: 'type', payload: '(' },
        { timestamp: 4900, type: 'type', payload: ')' },
        { timestamp: 4950, type: 'type', payload: ' ' },
        { timestamp: 5000, type: 'type', payload: '{' },
        { timestamp: 5050, type: 'type', payload: '\n' },

        { timestamp: 6500, type: 'type', payload: '    ' },
        { timestamp: 6600, type: 'type', payload: 'l' },
        { timestamp: 6650, type: 'type', payload: 'o' },
        { timestamp: 6700, type: 'type', payload: 'n' },
        { timestamp: 6750, type: 'type', payload: 'g' },
        { timestamp: 6800, type: 'type', payload: ' ' },
        { timestamp: 6850, type: 'type', payload: 'l' },
        { timestamp: 6900, type: 'type', payload: 'o' },
        { timestamp: 6950, type: 'type', payload: 'n' },
        { timestamp: 7000, type: 'type', payload: 'g' },
        { timestamp: 7050, type: 'type', payload: ' ' },
        { timestamp: 7100, type: 'type', payload: 'n' },
        { timestamp: 7150, type: 'type', payload: ',' },
        { timestamp: 7200, type: 'type', payload: ' ' },
        { timestamp: 7250, type: 'type', payload: 'm' },
        { timestamp: 7300, type: 'type', payload: ',' },
        { timestamp: 7350, type: 'type', payload: ' ' },
        { timestamp: 7400, type: 'type', payload: 'a' },
        { timestamp: 7450, type: 'type', payload: ';' },
        { timestamp: 7500, type: 'type', payload: '\n' },

        { timestamp: 8100, type: 'type', payload: '    ' },
        { timestamp: 8200, type: 'type', payload: 'c' },
        { timestamp: 8250, type: 'type', payload: 'i' },
        { timestamp: 8300, type: 'type', payload: 'n' },
        { timestamp: 8350, type: 'type', payload: ' ' },
        { timestamp: 8400, type: 'type', payload: '>' },
        { timestamp: 8450, type: 'type', payload: '>' },
        { timestamp: 8500, type: 'type', payload: ' ' },
        { timestamp: 8550, type: 'type', payload: 'n' },
        { timestamp: 8600, type: 'type', payload: ' ' },
        { timestamp: 8650, type: 'type', payload: '>' },
        { timestamp: 8700, type: 'type', payload: '>' },
        { timestamp: 8750, type: 'type', payload: ' ' },
        { timestamp: 8800, type: 'type', payload: 'm' },
        { timestamp: 8850, type: 'type', payload: ' ' },
        { timestamp: 8900, type: 'type', payload: '>' },
        { timestamp: 8950, type: 'type', payload: '>' },
        { timestamp: 9000, type: 'type', payload: ' ' },
        { timestamp: 9050, type: 'type', payload: 'a' },
        { timestamp: 9100, type: 'type', payload: ';' },
    ]
};
