INSERT INTO universities (name, short_name, type, email_domain) VALUES
('Mansoura National University', 'MNU', 'national', 'mansnu.edu.eg'),
('New Mansoura University', 'NMU', 'national', 'nmu.edu.eg'),
('Badr University in Cairo', 'BUC', 'private', 'buc.edu.eg'),
('Badr University in Assiut', 'BUA', 'private', 'bua.edu.eg'),
('New Giza University', 'NGU', 'private', 'ngu.edu.eg'),
('Egypt University of Informatics', 'EUI', 'national', 'eui.edu.eg'),
('German International University', 'GIU', 'private', 'giu-uni.de'),
('ESLSCA University', 'ESLSCA', 'private', 'eslsca.edu.eg'),
('Horus University in Egypt', 'HORUS', 'private', 'horus.edu.eg'),
('Merit University', 'MERIT', 'private', 'merit.edu.eg'),
('Universities of Canada in Egypt', 'UofC', 'international', 'uofcanada.edu.eg'),
('European Universities in Egypt', 'EUE', 'international', 'eue.edu.eg'),
('The Knowledge Hub Universities', 'TKH', 'international', 'tkh.edu.eg'),
('University of Hertfordshire in Egypt', 'UH', 'international', 'herts.ac.uk'),
('Benha National University', 'BNU', 'national', 'bnu.edu.eg'),
('Zagazig National University', 'ZNU', 'national', 'znu.edu.eg'),
('Menoufia National University', 'MenuNU', 'national', 'mnu.menofia.edu.eg'),
('East Port Said National University', 'EPSNU', 'national', 'epsnu.edu.eg'),
('Ismailia National Ahleya University', 'INAU', 'national', 'inau.edu.eg'),
('Helwan National University', 'HNU', 'national', 'hnu.edu.eg'),
('Minia National University', 'MiniaNU', 'national', 'minianu.edu.eg'),
('Beni-Suef National University', 'BSNU', 'national', 'bsnu.edu.eg'),
('Assiut National University', 'ANU', 'national', 'anu.edu.eg'),
('South Valley National University', 'SVNU', 'national', 'svnu.edu.eg'),
('Alexandria National University', 'AlexNU', 'national', 'alexnu.edu.eg'),
('May University in Cairo', 'MUC', 'private', 'muc.edu.eg'),
('Al-Salam University', 'SU', 'private', 'salam.edu.eg'),
('Al-Hayah University', 'HU', 'private', 'hayah.edu.eg'),
('Lotus University', 'LU', 'private', 'lotus.edu.eg'),
('Borg El Arab Technological University', 'BATU', 'technological', 'batu.edu.eg'),
('New Cairo Technological University', 'NCTU', 'technological', 'nctu.edu.eg'),
('Delta Technological University', 'DTU', 'technological', 'dtu.edu.eg'),
('Beni-Suef Technological University', 'BSTU', 'technological', 'bstu.edu.eg'),
('Assiut Technological University', 'ATU', 'technological', 'atu.edu.eg'),
('Taiba Technological University', 'TTU', 'technological', 'ttu.edu.eg'),
('6th of October Technological University', 'SOTU', 'technological', 'sotu.edu.eg')
ON CONFLICT DO NOTHING;
